services:
  face_recognition_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data    
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=:1
    container_name: face_recognition_app
    devices:
      - "/dev/video0:/dev/video0"
    extra_hosts:
      - "host.docker.internal:host-gateway"
